apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic-gmcq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic-gmcq
    app.kubernetes.io/part-of: devfile-sample-go-basic
  name: devfile-sample-go-basic-gmcq
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: devfile-sample-go-basic-gmcq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: devfile-sample-go-basic-gmcq
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/somahesh-tenant/devfile-sample-go-basic/devfile-sample-go-basic-gmcq@sha256:2ed763a3e01e5a1f412ece80d01854c4c169cb28aeb9b0de6d9efe4412c8e00c
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
